name: mess
favicon: null
layout_spectrum: 0.17045764019712806
typography_spectrum: 0.0003702663816511631
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7393126643728465
  lightness: 0.2945753252133727
  saturation: 0.9006100371479988
  rhythmicContrast: 0.8235626094974577
purpose: []
